#!/usr/bin/env ruby

require 'rubygems'
require 'optparse'
require 'opengl'
include Gl, Glu, Glut

OPTIONS = {}
OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    OPTIONS[:verbose] = v
  end

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end

end.parse!

$:.unshift(File.expand_path("../lib", __FILE__))

def puts(*args)
  STDOUT.puts(*args) if OPTIONS[:verbose]
end

require 'game'
